"""`warden profile` — detonate a skill and generate a least-privilege policy.

The supply-chain problem with agent skills is that static scanners can't see
what a skill *does* at runtime (a 2026 result showed >90% evasion). Warden's
answer is behavioral: run the skill once under Warden, observe exactly which
hosts it reaches, and emit a policy that allows precisely those and nothing else.

Safety: by default profiling runs with filesystem protection ON (secrets denied
by the sandbox) and egress CONTAINED — every host the skill tries to reach is
recorded but not actually connected, so profiling an untrusted skill cannot
leak. Pass allow_egress=True for a fuller run that lets connections through to
reveal second-order hosts (use only for skills you already partly trust).
"""

from __future__ import annotations

import os
import time
from pathlib import Path

from . import agents, sessions
from .policy import (DEFAULT_SECRET_DENY, FilesystemRules, NetworkRules, Policy,
                     ProcessRules, to_yaml)
from .runner import run


def known_good_hosts() -> set[str]:
    """Hosts Warden recognizes as ordinary developer/agent infrastructure."""
    hosts = set(agents.DEVELOPER_BASELINE)
    for a in agents.REGISTRY.values():
        hosts.update(a.egress)
    return hosts


def _host_is_known(host: str, known: set[str]) -> bool:
    import fnmatch

    host = host.lower()
    for k in known:
        k = k.lower()
        if k == host or fnmatch.fnmatch(host, k):
            return True
        # treat a bare known domain as covering its subdomains
        if host.endswith("." + k):
            return True
    return False


def classify_hosts(hosts: list[str]) -> tuple[list[str], list[str]]:
    """Split observed hosts into (recognized, unrecognized-for-review)."""
    known = known_good_hosts()
    recognized, review = [], []
    for h in hosts:
        (recognized if _host_is_known(h, known) else review).append(h)
    return recognized, review


def _profiling_policy(workdir: str, allow_egress: bool) -> Policy:
    return Policy(
        name="profiling",
        description="Temporary profiling policy: fs protected, egress recorded.",
        filesystem=FilesystemRules(
            read=[workdir + "/**", "~/.gitconfig"],
            write=[workdir + "/**", "/tmp/**", "/private/tmp/**"],
            deny=list(DEFAULT_SECRET_DENY),
        ),
        # allow=["*"] lets connections through and records them; [] records the
        # attempted host and blocks the connection (safe default).
        network=NetworkRules(allow=["*"] if allow_egress else [], deny=[],
                             deny_all_other=True),
        process=ProcessRules(deny=["ssh", "scp"]),
        on_violation="block+receipt",
    )


def profile(argv: list[str], *, agent: str | None = None, allow_egress: bool = False,
            out_path: str | None = None) -> tuple[int, Policy]:
    """Run `argv` under a profiling policy and synthesize a least-privilege policy."""
    workdir = os.getcwd()

    # Resolve an agent name to its launch command if given.
    if agent:
        a = agents.get(agent)
        if not a:
            raise SystemExit(f"warden: unknown agent '{agent}'")
        cmd = agents.resolve_command(a)
        if not cmd:
            raise SystemExit(f"warden: '{a.name}' is not installed")
        argv = cmd + argv

    stamp = "profile-" + time.strftime("%Y%m%d-%H%M%S")
    pol = _profiling_policy(workdir, allow_egress)
    code = run(argv, pol, enforce=True, session=stamp, agent=agent)

    summary = sessions.summarize(stamp)
    hosts = sorted({e["host"] for e in summary["allowed"]} |
                   {e["host"] for e in summary["blocked"]})

    generated = Policy(
        name=(agent or Path(argv[0]).name) + "-profile",
        description=f"Generated by `warden profile` from observed behavior "
                    f"({len(hosts)} host(s), session {stamp}).",
        filesystem=FilesystemRules(
            read=[workdir + "/**", "~/.gitconfig"],
            write=[workdir + "/**", "/tmp/**"],
            deny=list(DEFAULT_SECRET_DENY),
        ),
        network=NetworkRules(allow=hosts, deny=[], deny_all_other=True),
        process=ProcessRules(deny=["ssh", "scp", "aws", "gcloud", "kubectl"]),
        on_violation="block+receipt",
    )

    recognized, review = classify_hosts(hosts)

    if out_path:
        Path(out_path).write_text(to_yaml(generated), encoding="utf-8")

    return code, generated, {"recognized": recognized, "review": review, "session": stamp}
